#!/bin/bash
# Copyright (C) 2011-2013 OpenStack Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

# workaround a broken maintainer script in iptables-persistent that
# assumes it can execute things during postinst. Since we're installing
# in a chroot, we're actually not running the right kernel for its assumptions
# to work.

# If lsb_release is missing, just do nothing.
DISTRO=`lsb_release -si` || true

case $DISTRO in
    'Ubuntu'|'Debian')
    PRESEED=`mktemp`
    cat > $PRESEED <<EOF
d-i iptables-persistent/autosave_done boolean true
d-i iptables-persistent/autosave_v4 boolean false
d-i iptables-persistent/autosave_v6 boolean false
EOF
    debconf-set-selections $PRESEED
    rm $PRESEED
    ;;
esac
