#!/bin/sh

set -e

apt-get -y install --force-yes lsb-release
release=`lsb_release  --codename -s`

if test `lsb_release --id --short` = "Ubuntu"
then

    apt-get -y install --force-yes python-software-properties

    cat > "/etc/apt/sources.list.d/extras.list" << EOF
deb http://security.ubuntu.com/ubuntu $release-security main universe
deb-src http://security.ubuntu.com/ubuntu $release-security main universe
deb http://us.archive.ubuntu.com/ubuntu/ $release-updates main universe
deb-src http://us.archive.ubuntu.com/ubuntu/ $release-updates main universe

deb http://packages.openstack.org/trunk $release main
deb-src http://packages.openstack.org/trunk $release main
EOF

    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 32EE128C
    rm -rf /etc/apt/sources.list.d/nova-core*
else
    # Have I mentioned our lack of debian is a bit assy? Let's hope Maverick
    # works for now
    cat > "/etc/apt/sources.list.d/extras.list" << EOF
deb http://packages.openstack.org/trunk $release main
deb-src http://packages.openstack.org/trunk $release main
EOF
    rm -rf /etc/apt/sources.list.d/nova.list
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 32EE128C
fi

apt-get update
