#!/bin/bash
# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

DIST=$(lsb_release -is)
[ -n "$DIST" ]
case $DIST in
    'Ubuntu'|'Debian')
        sftp_location='/usr/lib/openssh/sftp-server'
        ;;
    'Fedora'|'CentOS')
        sftp_location='/usr/libexec/openssh/sftp-server'
        ;;
esac

# Install the sshd_config file. It's not exactly the same as the one that we
# ultimately want in place via puppet - mainly because it permits root login
# from everywhere. That's so that it can be used as a base from anywhere.
# Then, first thing we do is run puppet, so we can install both our personal
# keys and lock down root logins
# We install it so that when we boot and regenerate host keys, the config
# of which host keys to generate will be accurate
install -m 0444 -o root -g root $(dirname $0)/../files/sshd_config /etc/ssh/sshd_config
echo "Subsystem sftp $sftp_location" >> /etc/ssh/sshd_config
