---
- hosts: 'zuul.openstack.org'
  any_errors_fatal: true
  tasks:
    - name: Stop Zuul
      service:
        name: zuul
        state: stopped
      become: true
      become_user: root
    - name: Wait for (3h10m) to stop zuul
      wait_for:
        path: /var/run/zuul/zuul.pid
        state: absent
        timeout: 11400

- hosts: 'zlstatic0*.openstack.org:zl0*.openstack.org'
  tasks:
    - name: Hard stop zuul-launcher
      shell: 'zuul-launcher stop'
      become: true
      become_user: zuul

    - name: Wait for (3h10m) to stop zuul-launcher
      wait_for:
        path: /var/run/zuul-launcher/zuul-launcher.pid
        state: absent
        timeout: 11400

- hosts: 'zm0*.openstack.org'
  tasks:
    - name: Hard stop zuul-merger
      service:
        name: zuul-merger
        state: stopped
      become: true
      become_user: root
    - name: Wait for (3h10m) to stop zuul-merger
      wait_for:
        path: /var/run/zuul-merger/zuul-merger.pid
        state: absent
        timeout: 11400
