class openstack_project::infracloud::controller (
  $keystone_rabbit_password,
  $neutron_rabbit_password,
  $nova_rabbit_password,
  $root_mysql_password,
  $keystone_mysql_password,
  $glance_mysql_password,
  $neutron_mysql_password,
  $nova_mysql_password,
  $glance_admin_password,
  $keystone_admin_password,
  $neutron_admin_password,
  $nova_admin_password,
  $keystone_admin_token,
  $ssl_chain_file_contents,
  $keystone_ssl_key_file_contents,
  $keystone_ssl_cert_file_contents,
  $neutron_ssl_key_file_contents,
  $neutron_ssl_cert_file_contents,
  $glance_ssl_key_file_contents,
  $glance_ssl_cert_file_contents,
  $nova_ssl_key_file_contents,
  $nova_ssl_cert_file_contents,
  $br_name,
  $controller_management_address,
  $controller_public_address = $::fqdn,
  $quota_instances = 10,
  $quota_cores = 20,
  $quota_ram = 51200,
) {
  class { '::infracloud::controller':
    keystone_rabbit_password         => $keystone_rabbit_password,
    neutron_rabbit_password          => $neutron_rabbit_password,
    nova_rabbit_password             => $nova_rabbit_password,
    root_mysql_password              => $root_mysql_password,
    keystone_mysql_password          => $keystone_mysql_password,
    glance_mysql_password            => $glance_mysql_password,
    neutron_mysql_password           => $neutron_mysql_password,
    nova_mysql_password              => $nova_mysql_password,
    keystone_admin_password          => $keystone_admin_password,
    glance_admin_password            => $glance_admin_password,
    neutron_admin_password           => $neutron_admin_password,
    nova_admin_password              => $nova_admin_password,
    keystone_admin_token             => $keystone_admin_token,
    ssl_chain_file_contents          => $ssl_chain_file_contents,
    keystone_ssl_key_file_contents   => $keystone_ssl_key_file_contents,
    keystone_ssl_cert_file_contents  => $keystone_ssl_cert_file_contents,
    glance_ssl_key_file_contents     => $neutron_ssl_key_file_contents,
    glance_ssl_cert_file_contents    => $neutron_ssl_cert_file_contents,
    neutron_ssl_key_file_contents    => $glance_ssl_key_file_contents,
    neutron_ssl_cert_file_contents   => $glance_ssl_cert_file_contents,
    nova_ssl_key_file_contents       => $nova_ssl_key_file_contents,
    nova_ssl_cert_file_contents      => $nova_ssl_cert_file_contents,
    br_name                          => $br_name,
    controller_management_address    => $controller_management_address,
    controller_public_address        => $controller_public_address,
    quota_instances                  => $quota_instances,
    quota_cores                      => $quota_cores,
    quota_ram                        => $quota_ram,
  }
}
