#!/bin/bash -x

HOSTNAME=`hostname`
HOST=148.251.46.180
SSH_HOST=root@$HOST
date=`date +"%d-%m-%y"`
day_of_week=`date +"%u"`
BACKUP_LOC="/ci-admin/images/ci-infra-backup/backups/"
puppetmaster="ci-puppetmaster.opencontrail.org.vmdk-$date.gz"
puppetdb="puppetdb.opencontrail.org.vmdk-$date.gz"
review="review.opencontrail.org.vmdk-$date.gz"
zuul="zuul.opencontrail.org.vmdk-$date.gz"
jenkins="jenkins.opencontrail.org.vmdk-$date.gz"
echo $puppetmaster $puppetdb $review $zuul $jenkins

ssh ${SSH_HOST} " ( 
	bash -x /root/backup.sh
) "

for vm in $puppetmaster $puppetdb $review $zuul $jenkins
do
	if [ $day_of_week -eq 7 ]; then
		scp root@148.251.46.180:/backups/$vm $BACKUP_LOC
		ssh root@148.251.46.180 rm /backups/$vm
	else
		if [ $vm -eq $review ]; then
			scp root@148.251.46.180:/backups/$vm $BACKUP_LOC
			ssh root@148.251.46.180 rm /backups/$vm
		fi
		echo "Done..."
	fi
done
