#! /bin/sh
### BEGIN INIT INFO
# Provides:             krb5-kpropd
# Required-Start:       $local_fs $remote_fs $network $syslog
# Required-Stop:        $local_fs $remote_fs $network $syslog
# X-Start-Before: $x-display-manager                                          
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    MIT Kerberos propagation daemon
# Description:          Starts, stops, or restarts the MIT kpropd.
### END INIT INFO

# Author: Sam Hartman <hartmans@mit.edu>
# Author: Russ Allbery <rra@debian.org>
#
# Based on the /etc/init.d/skeleton template as found in initscripts version
# 2.86.ds1-15.

PATH=/usr/sbin:/usr/bin:/sbin:/bin
DESC="Kerberos kpropd"
NAME=kpropd
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS=""
SCRIPTNAME=/etc/init.d/krb5-kpropd

# Exit if the package is not installed.
[ -x "$DAEMON" ] || exit 0

# Read configuration if it is present.
[ -r /etc/default/krb5-kpropd ] && . /etc/default/krb5-kpropd

# Get the setting of VERBOSE and other rcS variables.
[ -f /etc/default/rcS ] && . /etc/default/rcS

# Define LSB log functions (requires lsb-base >= 3.0-6).
. /lib/lsb/init-functions


# Return
#   0 if daemon has been started
#   1 if daemon was already running
#   2 if daemon could not be started
do_start_kpropd()
{
    start-stop-daemon --start --quiet --startas $DAEMON --name $NAME --test \
        > /dev/null || return 1
    start-stop-daemon --start --quiet --startas $DAEMON --name $NAME \
        -- $DAEMON_ARGS || return 2
}


# Return
#   0 if daemon has been stopped
#   1 if daemon was already stopped
#   2 if daemon could not be stopped
#   other if a failure occurred
do_stop_kpropd()
{
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --name $NAME
    RETVAL="$?"
    [ "$RETVAL" = 2 ] && return 2
    return "$RETVAL"
}


case "$1" in 
  start)
    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
    do_start_kpropd
    case "$?" in
      0|1)
            [ "$VERBOSE" != no ] && log_end_msg 0
        ;;
      2)
        [ "$VERBOSE" != no ] && log_end_msg 1
        ;;
    esac
    ;;

  stop)
    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
    do_stop_kpropd
    case "$?" in
      0|1)
        [ "$VERBOSE" != no ] && log_progress_msg "krb524d"
        ;;
      2)
        [ "$VERBOSE" != no ] && log_end_msg 1
        ;;
    esac
    ;;

  restart|force-reload)
    log_daemon_msg "Restarting $DESC" "$NAME"
    do_stop_kpropd
    case "$?" in
      0|1)
        do_start_kpropd
        case "$?" in
          0)
	  log_end_msg 0
	  ;;
          1|2)
            log_end_msg 1
            ;;
        esac
        ;;
      *)
        log_end_msg 1
        ;;
    esac
    ;;

  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;

  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
    exit 3
    ;;
esac

:
