# == Class: openstack_project::server
#
# A server that we expect to run for some time
class openstack_project::server (
  $iptables_public_tcp_ports = [],
  $iptables_public_udp_ports = [],
  $iptables_rules4           = [],
  $iptables_rules6           = [],
  $sysadmins                 = [],
  $certname                  = $::fqdn,
  $pin_puppet                = '3.',
  $ca_server                 = undef,
  $afs                       = false,
  $puppetmaster_server       = 'puppetmaster.openstack.org',
  $pypi_index_url            = 'https://pypi.python.org/simple',
  $pypi_trusted_hosts        = [
    'pypi.dwf.openstack.org',
    'pypi.iad.openstack.org',
    'pypi.ord.openstack.org',
    'pypi.region-b.geo-1.openstack.org',
  ],
  $enable_puppet                = false,
  $puppet_http_proxy            = undef,
  $puppet_https_proxy           = undef,
  $puppet_agent_http_proxy_host = undef,
  $puppet_agent_http_proxy_port = undef,
  $puppet_dns_alt_names         = undef,
  $puppet_environment_path      = '/etc/puppet/environments',
  $puppet_basemodule_path       = '/etc/puppet/modules',
  $puppet_environment_timeout   = 0,
  $puppet_store_configs         = true,
  $puppet_store_backend         = 'puppetdb',
  $puppet_reports               = 'store,puppetdb',
  $puppet_agent_runinterval     = 600,
  $puppet_release               = $::lsbdistcodename,
) {
  class { 'openstack_project::template':
    iptables_public_tcp_ports    => $iptables_public_tcp_ports,
    iptables_public_udp_ports    => $iptables_public_udp_ports,
    iptables_rules4              => $iptables_rules4,
    iptables_rules6              => $iptables_rules6,
    certname                     => $certname,
    pin_puppet                   => $pin_puppet,
    ca_server                    => $ca_server,
    afs                          => $afs,
    puppetmaster_server          => $puppetmaster_server,
    pypi_index_url               => $pypi_index_url,
    pypi_trusted_hosts           => $pypi_trusted_hosts,
    enable_puppet                => $enable_puppet,
    puppet_http_proxy            => $puppet_http_proxy,
    puppet_https_proxy           => $puppet_https_proxy,
    puppet_agent_http_proxy_host => $puppet_agent_http_proxy_host,
    puppet_agent_http_proxy_port => $puppet_agent_http_proxy_port,
    puppet_dns_alt_names         => $puppet_dns_alt_names,
    puppet_environment_path      => $puppet_environment_path,
    puppet_basemodule_path       => $puppet_basemodule_path,
    puppet_environment_timeout   => $puppet_environment_timeout,
    puppet_store_configs         => $puppet_store_configs,
    puppet_store_backend         => $puppet_store_backend,
    puppet_reports               => $puppet_reports,
    puppet_agent_runinterval     => $puppet_agent_runinterval,
    puppet_release               => $puppet_release,
  }
  class { 'exim':
    sysadmins => $sysadmins,
  }
}
