#!/usr/bin/env bash

set -x

# Disable http proxy to access openstack metadata
unset http_proxy

HOSTNAME=`curl -s http://169.254.169.254/openstack/2012-08-10/meta_data.json | python -m json.tool | \grep \"name\": | awk -F '\"' '{print $4}'`
SLAVE_MASTER=`curl -s http://169.254.169.254/openstack/2012-08-10/meta_data.json | python -m json.tool | \grep \"slave-master\": | awk -F '\"' '{print $4}'`
PORT=6002 # 22

if [ -z $SLAVE_MASTER ]; then
    SLAVE_MASTER=localhost
fi

echo HOSTNAME $HOSTNAME, SLAVE_MASTER $SLAVE_MASTER

# Check if this run needs to be skipped.
ssh -p $PORT root@$SLAVE_MASTER ls /root/ci-test/skip_jobs
if [ "$?" == "0" ]; then
    echo Jobs skipped due to jenkins.opencontrail.org:/root/ci-test/skip_jobs
    exit 0
fi

echo $HOSTNAME > /etc/hostname
service hostname restart

if [ "$SLAVE_MASTER" != "localhost" ]; then
    # Set http proxy in sub-slaves
    export http_proxy=http://$SLAVE_MASTER:3128 # squid
    export https_proxy=http://$SLAVE_MASTER:3128 # squid
    export ftp_proxy=http://$SLAVE_MASTER:3128 # squid

    proxy="export http_proxy=$http_proxy"
    grep --quiet "$proxy" /etc/bash.bashrc
    if [ "$?" != "0" ]; then
        echo "$proxy" >> /etc/bash.bashrc
    fi
    proxy="export https_proxy=$https_proxy"
    grep --quiet "$proxy" /etc/bash.bashrc
    if [ "$?" != "0" ]; then
        echo "$proxy" >> /etc/bash.bashrc
    fi
    proxy="export ftp_proxy=$ftp_proxy"
    grep --quiet "$proxy" /etc/bash.bashrc
    if [ "$?" != "0" ]; then
        echo "$proxy" >> /etc/bash.bashrc
    fi

    # Set proxy for apt as well, if it is not already set.
    apt_proxy="Acquire::http::Proxy \"http://$SLAVE_MASTER:3128\";"
    grep --quiet "$apt_proxy" /etc/apt/apt.conf
    if [ "$?" != "0" ]; then
        echo "$apt_proxy" >> /etc/apt/apt.conf
    fi
fi

BRANCH=master
ssh -p $PORT root@$SLAVE_MASTER ls /root/ci-test/\*$HOSTNAME\*-test
if [ "$?" == "0" ]; then
    BRANCH=test
fi

# Copy slave scripts from the jenkins.opencontrail.org central master location.
rm -rf /usr/local/jenkins/slave_scripts /root/contrail-infra-config
git clone -b $BRANCH https://github.com/Juniper/contrail-infra-config.git /root/contrail-infra-config
ln -sf /root/contrail-infra-config/modules/jenkins/files/slave_scripts /usr/local/jenkins/slave_scripts
# ssh root@$SLAVE_MASTER -p $PORT tar zcf - /usr/local/jenkins/slave_scripts | tar -zx -C /

set -o pipefail
set -e

# Run the real script
cmd=$1
shift
exec $cmd $*
