#!/usr/bin/env bash

set -x

# Disable http proxy to access openstack metadata
unset http_proxy

HOSTNAME=`curl -s http://169.254.169.254/openstack/2012-08-10/meta_data.json | python -m json.tool | \grep \"name\": | awk -F '\"' '{print $4}'`
SLAVE_MASTER=`curl -s http://169.254.169.254/openstack/2012-08-10/meta_data.json | python -m json.tool | \grep \"slave-master\": | awk -F '\"' '{print $4}'`
PORT=6002 # 22

if [ -z $SLAVE_MASTER ]; then
    SLAVE_MASTER=localhost
fi

echo HOSTNAME $HOSTNAME, SLAVE_MASTER $SLAVE_MASTER

if [ "$SLAVE_MASTER" != "localhost" ]; then
    # Set http proxy in sub-slaves
    export http_proxy=http://$SLAVE_MASTER:3128 # squid
    export https_proxy=http://$SLAVE_MASTER:3128 # squid
    export ftp_proxy=http://$SLAVE_MASTER:3128 # squid

    proxy="export http_proxy=$http_proxy"
    grep --quiet "$proxy" /etc/bash.bashrc
    if [ "$?" != "0" ]; then
        echo "$proxy" >> /etc/bash.bashrc
    fi
    proxy="export https_proxy=$https_proxy"
    grep --quiet "$proxy" /etc/bash.bashrc
    if [ "$?" != "0" ]; then
        echo "$proxy" >> /etc/bash.bashrc
    fi
    proxy="export ftp_proxy=$ftp_proxy"
    grep --quiet "$proxy" /etc/bash.bashrc
    if [ "$?" != "0" ]; then
        echo "$proxy" >> /etc/bash.bashrc
    fi

    # Set proxy for apt as well, if it is not already set.
    apt_proxy="Acquire::http::Proxy \"http://$SLAVE_MASTER:3128\";"
    grep --quiet "$apt_proxy" /etc/apt/apt.conf
    if [ "$?" != "0" ]; then
        echo "$apt_proxy" >> /etc/apt/apt.conf
    fi

    # Set ssh-proxy for root and jenkins users.
    grep --quiet "ProxyCommand" /root/.ssh/config
    if [ "$?" != "0" ]; then
        echo ProxyCommand /usr/bin/corkscrew $SLAVE_MASTER 3128 %h %p >> /root/.ssh/config
    fi

    grep --quiet "ProxyCommand" /home/jenkins/.ssh/config
    if [ "$?" != "0" ]; then
        echo ProxyCommand /usr/bin/corkscrew $SLAVE_MASTER 3128 %h %p >> /home/jenkins/.ssh/config
        chown jenkins.jenkins /home/jenkins/.ssh/config
    fi
fi

# Work around for kernel tun/tap driver bug
# https://bugzilla.kernel.org/show_bug.cgi?id=60620
ssh root@jenkins.opencontrail.org ls /root/ci-test/skip_gso_disable
if [ "$?" != "0" ]; then
    /sbin/ethtool --offload eth0 tx off
    /sbin/ethtool --offload eth0 tso off
    /sbin/ethtool --offload eth0 ufo off
    /sbin/ethtool --offload eth0 gso off
fi

rm -rf /tmp/cache
ln -sf /home/jenkins/tmp/cache /tmp/cache

echo $HOSTNAME > /etc/hostname
service hostname restart

# Setup VM emulation if vmx support is not available
grep -q vmx /proc/cpuinfo
if [ "$?" != "0" ]; then
    if [ -f /etc/nova/nova-compute.conf ]; then
        perl -ni -e 's/libvirt_type=kvm/libvirt_type=qemu/g; print $_' /etc/nova/nova-compute.conf
        service nova-compute restart
    fi
fi
