- name: Kerberos and OpenAFS client installation
  hosts: base
  roles:
    - role: kerberos-client
      kerberos_realm: 'OPENSTACK.ORG'
      kerberos_admin_server: 'kdc.openstack.org'
      kerberos_kdcs:
        - kdc03.openstack.org
        - kdc04.openstack.org

    - role: openafs-client

  tasks:
    - name: Check for directory in /afs
      stat:
        path: "/afs/openstack.org/mirror"
      register: afs_mirror

    - name: Ensure that AFS is mounted
      assert:
        that:
          - afs_mirror.stat.exists

