#!/bin/sh

# Use timeout to kill any process running longer than 10 minutes.
timeout -k 2m 10m /usr/local/bin/update-bug change-merged "$@"
timeout -k 2m 10m /usr/local/bin/notify-impact change-merged "$@" --impact DocImpact --dest-address 'openstack-docs@lists.openstack.org' --auto-subscribers /home/gerrit2/review_site/hooks/subscriber_map.yaml
