var ciNames = ["Jenkins",
               "Arista Testing",
               "Big Switch CI",
               "Brocade CI",
               "Cisco Neutron CI",
               "Elastic Recheck",
               "Embrane CI",
               "Freescale CI",
               "Huawei CI",
               "Hyper-V CI",
               "IBM Neutron Testing",
               "IBM PowerKVM Testing",
               "Mellanox External Testing",
               "Metaplugin CI Test",
               "Midokura CI Bot",
               "NEC OpenStack CI",
               "Neutron Ryu",
               "Nuage CI",
               "One Convergence CI",
               "OpenDaylight Jenkins",
               "PLUMgrid CI",
               "Radware 3rd Party Testing",
               "Red Hat CI",
               "SmokeStack",
               "VMware Mine Sweeper",
               "XenServer CI",
               "turbo-hipster",
              ];
