#!/bin/sh

# Use timeout to kill any process running longer than 10 minutes.
timeout -k 2m 10m python /usr/local/gerrit/scripts/update_blueprint.py patchset-created "$@"
timeout -k 2m 10m python /usr/local/gerrit/scripts/update_bug.py patchset-created "$@"
timeout -k 2m 10m python /usr/local/gerrit/scripts/notify_doc_impact.py patchset-created "$@"
