queues:
  - name: check
    manager: IndependentQueueManager
    trigger:
      - event: patchset-created
    success:
      verified: 1
    failure:
      verified: -1
  - name: gate
    manager: DependentQueueManager
    trigger:
      - event: comment-added
        approval:
          - approved: 1
    success:
      verified: 2
      submit: true
    failure:
      verified: -2
  - name: post
    manager: IndependentQueueManager
    trigger:
      - event: ref-updated
        ref: ^(?!refs/).*$

jobs:
  - name: ^.*-merge$
    failure-message: This change was unable to be automatically merged with the current state of the repository. Please rebase your change and upload a new patchset.

projects:
  - name: openstack-ci/zuul
    check:
      - gate-zuul-merge:
        - gate-zuul-pep8
        - gate-zuul-pyflakes
    gate:
      - gate-zuul-merge:
        - gate-zuul-pep8
        - gate-zuul-pyflakes
  - name: openstack-ci/pypi-mirror
    check:
      - gate-pypi-mirror-merge:
        - gate-pypi-mirror-pyflakes
    gate:
      - gate-pypi-mirror-merge:
        - gate-pypi-mirror-pyflakes
  - name: openstack-ci/gerrit
    check:
      - gate-gerrit-merge:
        - check-gerrit-unittests
    gate:
      - gate-gerrit-merge:
        - gate-gerrit-unittests
    post:
      - gerrit-package
