queues:
  - name: check
    manager: IndependentQueueManager
    trigger:
      - event: patchset-created
    success:
      verified: 1
    failure:
      verified: -1

  - name: gate
    manager: DependentQueueManager
    trigger:
      - event: comment-added
        approval:
          - approved: 1
    success:
      verified: 2
      submit: true
    failure:
      verified: -2

  - name: post
    manager: IndependentQueueManager
    trigger:
      - event: ref-updated
        ref: ^(?!refs/).*$

jobs:
  - name: ^.*-merge$
    failure-message: This change was unable to be automatically merged with the current state of the repository. Please rebase your change and upload a new patchset.

projects:
  - name: stackforge/ceilometer
    check:
      - gate-ceilometer-merge:
        - gate-ceilometer-pep8
        - gate-ceilometer-python26
        - gate-ceilometer-python27
        - gate-ceilometer-python26-essex
        - gate-ceilometer-python27-essex
    gate:
      - gate-ceilometer-merge:
        - gate-ceilometer-pep8
        - gate-ceilometer-python26
        - gate-ceilometer-python27

  - name: heat-api/heat
    check:
      - gate-heat-merge:
        - gate-heat-pep8
        - gate-heat-python26
        - gate-heat-python27
    gate:
      - gate-heat-merge:
        - gate-heat-pep8
        - gate-heat-python26
        - gate-heat-python27

  - name: stackforge/reddwarf
    check:
      - gate-reddwarf-merge:
        - gate-reddwarf-pep8
        - gate-reddwarf-python26
        - gate-reddwarf-python27
    gate:
      - gate-reddwarf-merge:
        - gate-reddwarf-pep8
        - gate-reddwarf-python26
        - gate-reddwarf-python27
