#!/bin/bash
# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu
set -o pipefail

cd /tmp/nova-agent
./installer.sh
sed '1i### BEGIN INIT INFO\n# Provides: Nova-Agent\n# Required-Start: $remote_fs $syslog\n# Required-Stop: $remote_fs $syslog\n# Default-Start: 2 3 4 5\n# Default-Stop: 0 1 6\n# Short-Description: Start daemon at boot time\n# Description: Enable service provided by daemon.\n### END INIT INFO\n' /usr/share/nova-agent/1.39.0/etc/generic/nova-agent > /usr/share/nova-agent/1.39.0/etc/generic/nova-agent.lsb
cp -av /usr/share/nova-agent/1.39.0/etc/generic/nova-agent.lsb /etc/init.d/nova-agent
chmod +x /etc/init.d/nova-agent

# cloud-init / nova-agent sad panda hacks
cat > /etc/init/cloud-init-local.conf <<'EOF'
# cloud-init - the initial cloud-init job
#   crawls metadata service, emits cloud-config
start on mounted MOUNTPOINT=/

task

console output

pre-start script
    /etc/init.d/xe-linux-distribution start
    sleep 2
    /etc/init.d/nova-agent start
    sleep 13
    ifdown -a
    ifup -a
end script

exec /usr/bin/cloud-init init --local
EOF

cat > /etc/cloud/cloud.cfg.d/80_restart_network.cfg <<'EOF'
# Restart networking if it's got no IP. This is to catch if we're on RAX
# and the baked in dhcp config didn't work, but is now probably reconfigured
# by nova-agent
runcmd:
 - ip addr show eth0 | grep inet || ( ifdown -a ; ifup -a )
EOF


# stop nova-agent from starting twice since we start it from cloud-init now
update-rc.d -f nova-agent remove
update-rc.d -f xe-linux-distribution remove

# console fix for PV Ubuntus
cat > /etc/init/hvc0.conf <<'EOF'

# hvc0 - getty
#
# This service maintains a getty on hvc0 from the point the system is
# started until it is shut down again.

start on stopped rc or RUNLEVEL=[2345]
stop on runlevel [!2345]

respawn
exec /sbin/getty -L 115200 hvc0 vt102
EOF
