name 'puppetlabs-puppetdb'
version '3.0.0'
source 'git://github.com/puppetlabs/puppetlabs-puppetdb.git'
author 'Puppet Labs'
description 'PuppetDB resource types'
summary 'PuppetDB resource types'
license 'ASL 2.0'
project_page 'https://github.com/puppetlabs/puppetlabs-puppetdb'

dependency 'puppetlabs/inifile', '1.x'
dependency 'puppetlabs/postgresql', '>= 3.1.0 <4.0.0'
dependency 'puppetlabs/firewall', '>= 0.0.4'
dependency 'puppetlabs/stdlib', '>= 2.2.0'
