#!/bin/bash

set -eu
set -o pipefail

[ -n "$TARGET_ROOT" ]

# During image build, sync calls are expensive overhead
echo 'force-unsafe-io' | sudo tee $TARGET_ROOT/etc/dpkg/dpkg.cfg.d/02apt-speedup > /dev/null

# we want to effectively run "apt-get clean" after every install to keep
# images small (see output of "apt-get clean -s" for context)
{
    aptGetClean='"rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true";'
    echo "DPkg::Post-Invoke { ${aptGetClean} };"
    echo "APT::Update::Post-Invoke { ${aptGetClean} };"
    echo 'Dir::Cache::pkgcache ""; Dir::Cache::srcpkgcache "";'
} | sudo tee $TARGET_ROOT/etc/apt/apt.conf.d/no-cache > /dev/null

# and remove the translations, too
echo 'Acquire::Languages "none";' | sudo tee $TARGET_ROOT/etc/apt/apt.conf.d/no-languages > /dev/null
