- hosts: "localhost:!disabled"
  name: "System-config: Update the system-config repo on bridge"
  connection: local
  gather_facts: false
  tasks:
    - name: Make sure system-config repo is up to date
      git:
        repo: https://git.openstack.org/openstack-infra/system-config
        dest: /opt/system-config
        force: yes

    - name: Clone puppet modules to /etc/puppet/modules
      command: ./install_modules.sh
      args:
        chdir: /opt/system-config

    - name: Install ansible roles to /etc/ansible/roles
      command: ansible-galaxy install --roles-path /etc/ansible/roles --force -r roles.yaml
      args:
        chdir: /opt/system-config
