#!/bin/bash
# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu
set -o pipefail

DIST=$(lsb_release -is)
[ -n "$DIST" ]
case $DIST in
    'Ubuntu'|'Debian')
        sftp_location='/usr/lib/openssh/sftp-server'
        ;;
    'Fedora'|'CentOS')
        sftp_location='/usr/libexec/openssh/sftp-server'
        ;;
esac

install -m 0444 -o root -g root $(dirname $0)/../files/sshd_config /etc/ssh/sshd_config

sed -i -e "s/%%SFTP_LOCATION%%/$sftp_location/" /etc/ssh/sshd_config
