#!/bin/bash
set -e

# Unset the download cache for this invocation to prevent bleed from build host
unset PIP_DOWNLOAD_CACHE
/bin/bash /root/install_puppet.sh
/bin/bash /tmp/config/install_modules.sh
